//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodePlex.Migration.WorkItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodePlex.Migration.WorkItems.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding work item {0} on target endpoint.
        /// </summary>
        internal static string AddingWorkItem {
            get {
                return ResourceManager.GetString("AddingWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to.
        /// </summary>
        internal static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting migration.
        /// </summary>
        internal static string BeginMigrationMessage {
            get {
                return ResourceManager.GetString("BeginMigrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePlex work item ID.
        /// </summary>
        internal static string CodePlexWorkItemId {
            get {
                return ResourceManager.GetString("CodePlexWorkItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePlex work item ID not found in GitHub issue body.
        /// </summary>
        internal static string CodePlexWorkItemIdNotFoundInGitHubIssueBody {
            get {
                return ResourceManager.GetString("CodePlexWorkItemIdNotFoundInGitHubIssueBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}@{1}].
        /// </summary>
        internal static string CommentPostedByPersonXOnDateY {
            get {
                return ResourceManager.GetString("CommentPostedByPersonXOnDateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an issue that is labeled as both partially migrated and fully migrated OR multiple issues were found in specified GitHub repo that are associated with CodePlex work item ID {0}.
        /// </summary>
        internal static string EncounteredCollisionWorkItemIdX {
            get {
                return ResourceManager.GetString("EncounteredCollisionWorkItemIdX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error extracting CodePlex work item ID from GitHub issue #{0}: {1}.
        /// </summary>
        internal static string ErrorExtractingCodePlexWorkItemIdFromGitHubIssue {
            get {
                return ResourceManager.GetString("ErrorExtractingCodePlexWorkItemIdFromGitHubIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CodePlex work item ID {0}.
        /// </summary>
        internal static string InvalidCodePlexWorkItemId {
            get {
                return ResourceManager.GetString("InvalidCodePlexWorkItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue closed by {0} with comment.
        /// </summary>
        internal static string IssueClosedByXWithComment {
            get {
                return ResourceManager.GetString("IssueClosedByXWithComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception was encountered while running migration. Exception message: {0}.
        /// </summary>
        internal static string LogExceptionMessage {
            get {
                return ResourceManager.GetString("LogExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting work item {0} from CodePlex.
        /// </summary>
        internal static string LookupIndividualWorkItem {
            get {
                return ResourceManager.GetString("LookupIndividualWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving migrated work items from destination repository.
        /// </summary>
        internal static string LookupMigratedWorkItemsMessage {
            get {
                return ResourceManager.GetString("LookupMigratedWorkItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up the work items to migrate from CodePlex project.
        /// </summary>
        internal static string LookupWorkItemsToMigrate {
            get {
                return ResourceManager.GetString("LookupWorkItemsToMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work item was migrated from CodePlex.
        /// </summary>
        internal static string MigratedCodePlexWorkItemDetails {
            get {
                return ResourceManager.GetString("MigratedCodePlexWorkItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed successfully.
        /// </summary>
        internal static string MigrationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("MigrationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple issues were found in specified GitHub repo that are labeled with CodePlex work item ID {0}.
        /// </summary>
        internal static string MultipleIssuesFoundInGitHubRepoWithWorkItemIdX {
            get {
                return ResourceManager.GetString("MultipleIssuesFoundInGitHubRepoWithWorkItemIdX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issue was found in specified GitHub repo that corresponds to CodePlex work item ID {0}.
        /// </summary>
        internal static string NoIssueFoundInGitHubRepoWithWorkItemIdX {
            get {
                return ResourceManager.GetString("NoIssueFoundInGitHubRepoWithWorkItemIdX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress of migration will be slow in order to avoid triggering GitHub APIs abuse mechanisms. Please, refer to the following URL for more info: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits.
        /// </summary>
        internal static string ProgressOfMigrationWillBeSlow {
            get {
                return ResourceManager.GetString("ProgressOfMigrationWillBeSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason closed.
        /// </summary>
        internal static string ReasonClosed {
            get {
                return ResourceManager.GetString("ReasonClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting migration of {0} work items from CodePlex project to destination repository.
        /// </summary>
        internal static string StartingMigrationOfXWorkItems {
            get {
                return ResourceManager.GetString("StartingMigrationOfXWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot contain only whitespace characters.
        /// </summary>
        internal static string StringCannotBeAllWhiteSpace {
            get {
                return ResourceManager.GetString("StringCannotBeAllWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be empty.
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully migrated work item {0} [{1}/{2}] - &quot;{3}&quot;.
        /// </summary>
        internal static string SuccessfullyMigratedWorkItemIdXTitleY {
            get {
                return ResourceManager.GetString("SuccessfullyMigratedWorkItemIdXTitleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval must be greater than zero.
        /// </summary>
        internal static string TimeIntervalMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TimeIntervalMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration aborted due to an unrecoverable error. See the log file for full details of this run. If this is an intermittent issue, running this utility again with the same parameters will resume migration..
        /// </summary>
        internal static string UnrecoverableError {
            get {
                return ResourceManager.GetString("UnrecoverableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating work item {0} on target endpoint.
        /// </summary>
        internal static string UpdatingWorkItem {
            get {
                return ResourceManager.GetString("UpdatingWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not within allowed range.
        /// </summary>
        internal static string ValueIsNotWithinAllowedRange {
            get {
                return ResourceManager.GetString("ValueIsNotWithinAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote count.
        /// </summary>
        internal static string VoteCount {
            get {
                return ResourceManager.GetString("VoteCount", resourceCulture);
            }
        }
    }
}
